title: Dhia Permata Salsabila # your name (or website title) here
logo: "/images/DHIA PERMATA SALSABILA_PHOTO.JPEG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Penultimate year Physics student at Bandung Institute of Technology 
  <br><br>
  Student at PZSIB Data Warehousing, Analysis, and Visualizations for Business Insight 
  <br><br>
  <a href="https://www.linkedin.com/in/dhiapermatasalsabila/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
